### ISSUE TITLE
getchildren() deprecation in Python 3.9

### ISSUE THREAD

**Issue by sharkusd** [AdvancedPhotonSource/rsMap3D#1]
getchildren() for no longer works for Python 3.9 and rsMap3D does not run. To fix the issue, replace all lines in \Anaconda3\Lib\site-packages\rsMap3D\datasource\InstForXrayutilitiesReader.py which have 

"return _object_.getchildren()"
:return list(_object_)"

for example on line 77
"return self.root.find(DETECTOR_CIRCLES).getchildren()"  becomes
"return list(self.root.find(DETECTOR_CIRCLES)))

**Comment by JPHammonds** [comment]
Fixed
